#!/bin/sh
session=${2:-i3}

case $session in
    i3) exec i3;;
    dwm) picom -f &
	dunst &
	xss-lock --transfer-sleep-lock i3lock -c "#282a36" --nofork &
	#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
	setrgb &
	setbg &
	dwmblocks &
	exec dwm ;;
    *) exec $1;;
esac
