#!/bin/bash

vol(){
		vol="$(pamixer --get-volume-human)"
		vollev="$(pamixer --get-volume)"
		if [ "${vollev}" -eq "0" ]; then
				vollevbar="::::::::::"
		elif [ "${vollev}" -lt "10" ]; then
				vollevbar="|:::::::::"
		elif [ "${vollev}" -ge "10" ] && [ "${vollev}" -lt "20" ]; then
				vollevbar="||::::::::"
		elif [ "${vollev}" -ge "20" ] && [ "${vollev}" -lt "30" ]; then
				vollevbar="|||:::::::"
		elif [ "${vollev}" -ge "30" ] && [ "${vollev}" -lt "40" ]; then
				vollevbar="||||::::::"
		elif [ "${vollev}" -ge "40" ] && [ "${vollev}" -lt "50" ]; then
				vollevbar="|||||:::::"
		elif [ "${vollev}" -ge "50" ] && [ "${vollev}" -lt "60" ]; then
				vollevbar="||||||::::"
		elif [ "${vollev}" -ge "60" ] && [ "${vollev}" -lt "70" ]; then
				vollevbar="|||||||:::"
		elif [ "${vollev}" -ge "70" ] && [ "${vollev}" -lt "80" ]; then
				vollevbar="||||||||::"
		elif [ "${vollev}" -ge "80" ] && [ "${vollev}" -lt "90" ]; then
				vollevbar="||||||||::"
		elif [ "${vollev}" -ge "90" ] && [ "${vollev}" -lt "100" ]; then
				vollevbar="|||||||||:"
		elif [ "${vollev}" -eq "100" ]; then
				vollevbar="||||||||||"
		fi
				
		echo -e " ${vollevbar} ${vol}"
}

echo -e "$(vol)"
