#!/bin/bash
echo -en "1.\tDesktop\n2.\tTV\nEnter monitor: "
read monitor

if [ "$monitor" -eq 1 ]; then
		xrandr --output DP-4 --auto --output DP-3 --auto --left-of DP-4 --output HDMI-0 --off
else
		xrandr --output HDMI-0 --auto --output DP-4 --off --output DP-4 --off
fi
