#!/bin/bash

dt(){
		dt="$(date '+%m/%d/%Y %I:%M%p')"
		echo -e " $dt"
}

vol(){
		vol="$(pamixer --get-volume-human)"
		echo -e " $vol"
}

bat(){
		FILE=/sys/class/power_supply/BAT0
		if [ -e "$FILE" ]; then
				bat="$(cat $FILE/capacity)%"
				echo -e " ${bat} |"
		fi
}

wifi(){
		en="$(cat /sys/class/net/en*/operstate)"
		wf="$(cat /sys/class/net/w*/operstate)"
		if [ $en = "up" ]; then
				echo -e ""
		elif [ $wf = "up" ]; then
				wfsig=$(awk '/^\s*w/ {print int($3*100/70)}' /proc/net/wireless)
				echo -e " ${wfsig}%"
		else
				echo -e ""
		fi
}

while true; do
		xsetroot -name "$(bat) $(vol) | $(wifi) | $(dt)"
		sleep 1s
done
